# Site settings
author: Chaim (Kirill) Shcherbina
title: Chaim's blog
header-img: img/home-bg.png
email: rabbichaim770@gmail.com
copyright_name: Chaim (Kirill) Shcherbina
description: > # this means to ignore newlines until "baseurl:"
  Best blog ever
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ChaimSh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
